In [89]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/MarkystarkDotCO/Deep-Reinforcement-python/main/dataset.csv')

#df = df.to_frame()
#df.head()

In [90]:
import numpy as np   
from numpy import asarray

In [91]:
df.shape[0]

19999

In [92]:
y= df.iloc[ : , -1].to_frame()
#print(type(y))
#print(y)

In [93]:
x = df.iloc[:,:-1]

#print(type(x))

In [94]:
print(x.shape) 
print(y.shape) 

(19999, 81)
(19999, 1)


In [95]:
x = np.array(x)
print(x.size)
print(x)


1619919
[[1 0 0 ... 1 0 0]
 [1 0 0 ... 2 1 1]
 [1 0 0 ... 1 1 2]
 ...
 [1 0 0 ... 2 1 1]
 [1 0 0 ... 2 0 1]
 [1 0 0 ... 2 0 1]]


In [96]:

y= np.array(y)

print(y.size)
print(y)

19999
[[1]
 [1]
 [1]
 ...
 [1]
 [2]
 [2]]


In [ ]:
#from sklearn.datasets import load_boston
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
#import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

#boston = load_boston()
#x, y = boston.data, boston.target
#print(x.shape)

#x = x.reshape(x.shape[0], x.shape[1], 1)
#print(x.shape)

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.15)

model = Sequential()
model.add(Conv1D(64, 2, activation="relu", input_shape=(81,1)))
model.add(Dense(16, activation="relu"))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(3, activation = 'softmax'))


model.compile(loss = 'sparse_categorical_crossentropy', 
     optimizer = "adam",               
              metrics = ['accuracy'])

model.summary()
model.fit(xtrain, ytrain, batch_size=16,epochs=100, verbose=0)

acc = model.evaluate(xtrain, ytrain)
print("Loss:", acc[0], " Accuracy:", acc[1])

pred = model.predict(xtest)

pred_y = pred.argmax(axis=-1)

cm = confusion_matrix(ytest, pred_y)
print(cm)

print(" y test is", ytest[1])
print("y predicted is ", pred[1])

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_13 (Conv1D)          (None, 80, 64)            192       
                                                                 
 dense_21 (Dense)            (None, 80, 16)            1040      
                                                                 
 max_pooling1d_13 (MaxPoolin  (None, 40, 16)           0         
 g1D)                                                            
                                                                 
 flatten_8 (Flatten)         (None, 640)               0         
                                                                 
 dense_22 (Dense)            (None, 3)                 1923      
                                                                 
Total params: 3,155
Trainable params: 3,155
Non-trainable params: 0
____________________________________________________

In [ ]:
test_index = 2000

print("x test is   :::", xtest[test_index])
print(" y test is   :::", ytest[test_index])

max_value = np.max(pred[test_index])

predited_y = np.argmax(pred[test_index])
print("y predict is    :::", predited_y)


In [ ]:
table = xtest[:1]

write =""
raw = 71
for i in range(9):
  #print(table[0,raw])
  raw = raw+1
  write = write +"    "+str(table[0,raw])
  if i ==2 or i==5 or i==8:
    write = write +"\n"

print(write)
